# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ced1c23caf56b96a9a2045dcb17587f325d8359d0a4f5a6486b2db604fe08759f6f91c57ba5768353620731265bd54c365898cfc94be6baf207f7babb8bb35a

test:
  secret_key_base: 12e36d6ee8caaa93018f28bcfb9395d94df9411a9b5afc36067f611ef93ce2aff5d7da688441a7b579945e9d7d7cd06e82a80dc59049c3ed3f1af10d9b38b835

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
