dem: 2
email_maxlenth: 255
name_maxlenth: 50
password_minlenth: 6
size: 80
error: "error"
index: 
  size: 50
user:
  size: 50
  hours: 2
session_controller:
  number: "1"
micropost:
  number_maximum: 140
  number_micropost_html: 50
  picture_size: 5
user_info_html:
  number_size: 50
